steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",
          "-t", "botfront/actions-sdk:$TAG_NAME",
          "-t", "botfront/actions-sdk:latest",
          "."]
- name: 'gcr.io/cloud-builders/docker'
  args: [ "login", "-u", "$_DOCKER_USERNAME", "-p", "$_DOCKER_PASSWORD"]
- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/actions-sdk:$TAG_NAME"]
- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/actions-sdk:latest"]
